<?php

namespace App\Http\Controllers;

use App\Models\Payment;
use App\Models\Room;
use App\Models\Setting;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class PaymentController extends Controller
{
    public function index(Request $request): JsonResponse
    {
        // Auto-heal existing monthly rent invoices where due_date is incorrect
        Payment::where('invoice_type', 'monthly_rent')
            ->whereNotNull('billing_period_end')
            ->whereColumn('due_date', '!=', 'billing_period_end')
            ->chunkById(100, function ($payments) {
                foreach ($payments as $p) {
                    $p->update([
                        'due_date' => $p->billing_period_end,
                        'status' => ($p->status === 'overdue' && \Carbon\Carbon::parse($p->billing_period_end)->gt(now()->startOfDay()))
                            ? 'pending'
                            : $p->status
                    ]);
                }
            });

        $query = $this->scopeByOwner(Payment::with(['tenant', 'room.roomType']), $request);

        if ($status = $request->query('status')) $query->where('status', $status);
        if ($from = $request->query('from')) $query->whereDate('due_date', '>=', $from);
        if ($to = $request->query('to')) $query->whereDate('due_date', '<=', $to);
        if ($search = $request->query('search')) {
            $query->whereHas('tenant', fn($q) => $q->where('name', 'like', "%{$search}%"));
        }

        $sort = $request->query('sort', '-created_at');
        $direction = str_starts_with($sort, '-') ? 'desc' : 'asc';
        $query->orderBy(ltrim($sort, '-'), $direction);

        $payments = $query->paginate($request->query('limit', 10));
        
        $ownerIds = $payments->pluck('user_id')->unique()->filter()->toArray();
        $settingsMap = Setting::whereIn('user_id', $ownerIds)->get()->keyBy('user_id');

        $payments->getCollection()->transform(function ($p) use ($settingsMap) {
            // Dynamic overdue detection (monthly only)
            $status = $p->status;
            if ($status === 'pending' && $p->invoice_type === 'monthly_rent' && $p->due_date && $p->due_date->lt(now()->startOfDay())) {
                $status = 'overdue';
            }

            $settings = $settingsMap->get($p->user_id);

            return [
                'id' => $p->id, 
                'tenant' => $p->tenant->name ?? 'N/A',
                'room' => $p->room->room_number ?? 'N/A',
                'roomType' => $p->room->roomType->name ?? $p->room->type ?? 'Standard Suite',
                'billingCycle' => $p->room->roomType->billing_cycle ?? 'monthly',
                'amount' => $p->amount, 
                'lateFee' => $p->late_fee,
                'utilityAmount' => $p->utility_amount,
                'total' => $p->total,
                'dueDate' => $p->due_date, 
                'paidDate' => $p->paid_date,
                'status' => $status, 
                'month' => $p->month,
                'paymentMethod' => $p->payment_method,
                'receiptNumber' => $p->receipt_number,
                'autoGenerated' => $p->auto_generated,
                'contractId' => $p->contract_id,
                'invoiceType' => $p->invoice_type,
                'notes' => $p->notes,
                'billingPeriodStart' => $p->billing_period_start,
                'billingPeriodEnd' => $p->billing_period_end,
                'invoiceNumber' => $p->invoice_number ?? ('INV-' . strtoupper(substr($p->id, 0, 8))),
                'property' => [
                    'name' => $settings->property_name ?? 'RentFlow Property Group Ltd.',
                    'address' => $settings->address ?? 'Suite 500, 100 Innovation Way, Tech District',
                    'phone' => $settings->phone ?? '+1 (555) 123-4567',
                    'email' => $settings->email ?? 'billing@rentflow-pms.com',
                ]
            ];
        });

        return $this->paginated($payments);
    }

    public function late(Request $request): JsonResponse
    {
        // Include both explicitly overdue AND dynamically detected overdue
        $payments = $this->scopeByOwner(Payment::with(['tenant', 'room']), $request)
            ->where('invoice_type', 'monthly_rent')
            ->where(function ($q) {
                $q->where('status', 'overdue')
                  ->orWhere(function ($q2) {
                      $q2->where('status', 'pending')
                         ->whereDate('due_date', '<', now()->startOfDay());
                  });
            })
            ->orderBy('due_date', 'asc')->get()
            ->map(fn($p) => [
                'id' => $p->id, 'tenant' => $p->tenant->name ?? 'N/A',
                'room' => $p->room->room_number ?? 'N/A',
                'amount' => $p->amount, 'lateFee' => $p->late_fee,
                'total' => $p->total,
                'dueDate' => $p->due_date, 'status' => 'overdue',
                'month' => $p->month,
                'daysOverdue' => (int) $p->due_date->diffInDays(now()),
            ]);

        return $this->success($payments);
    }

    public function store(Request $request): JsonResponse
    {
        $v = $request->validate([
            'tenantId' => 'required|exists:tenants,id',
            'amount' => 'required|numeric|min:0',
            'paidDate' => 'nullable|date',
            'status' => 'nullable|in:pending,paid,overdue,cancelled,duplicate',
            'month' => 'required|string',
            'paymentMethod' => 'nullable|in:qr_code,credit_card',
            'dueDate' => 'nullable|date',
        ]);

        $status = $v['status'] ?? 'pending';
        $paidDate = null;

        if ($status === 'paid') {
            $paidDate = $v['paidDate'] ?? now()->format('Y-m-d');
        }

        $tenant = \App\Models\Tenant::find($v['tenantId']);
        $settings = Setting::where('user_id', $request->user()->id)->first() ?? Setting::first();
        $dueDay = $settings->invoice_due_day ?? 1;

        $contract = \App\Models\Contract::where('tenant_id', $v['tenantId'])
            ->where('status', 'active')
            ->first();
        if (!$contract) {
            $contract = \App\Models\Contract::where('tenant_id', $v['tenantId'])
                ->orderBy('created_at', 'desc')
                ->first();
        }

        $billingCycle = $contract?->billing_cycle ?? $tenant->room->roomType->billing_cycle ?? 'monthly';
        $invoiceType = $billingCycle === 'daily' ? 'daily_rental' : 'monthly_rent';

        if ($billingCycle === 'daily') {
            $billingPeriodStart = $contract?->start_date ? $contract->start_date->format('Y-m-d') : ($tenant->move_in_date ?? now()->format('Y-m-d'));
            $billingPeriodEnd = $contract?->end_date ? $contract->end_date->format('Y-m-d') : ($tenant->move_out_date ?? now()->addDay()->format('Y-m-d'));
        } else {
            $checkInDate = $contract?->start_date 
                ? \Carbon\Carbon::parse($contract->start_date) 
                : ($tenant->move_in_date 
                    ? \Carbon\Carbon::parse($tenant->move_in_date) 
                    : now()->startOfMonth());

            try {
                $targetDate = \Carbon\Carbon::parse($v['month']);
            } catch (\Exception $e) {
                $targetDate = now();
            }

            $checkInDay = $checkInDate->day;
            $daysInMonth = $targetDate->daysInMonth;
            $billingDay = min($checkInDay, $daysInMonth);
            
            $start = $targetDate->copy()->day($billingDay);
            $billingPeriodStart = $start->format('Y-m-d');
            $billingPeriodEnd = $start->copy()->addMonth()->format('Y-m-d');
        }

        $dueDate = $v['dueDate'] ?? null;
        if (!$dueDate) {
            if ($billingCycle === 'daily') {
                $defaultDate = now()->startOfMonth()->day($dueDay);
                // If the monthly due day has already passed, default to now + grace period days
                if ($defaultDate->lt(now()->startOfDay())) {
                    $dueDate = now()->addDays($settings->grace_period_days ?? 5)->format('Y-m-d');
                } else {
                    $dueDate = $defaultDate->format('Y-m-d');
                }
            } else {
                $dueDate = $billingPeriodEnd;
            }
        }

        $payment = Payment::create([
            'tenant_id' => $v['tenantId'],
            'room_id' => $tenant->room_id,
            'contract_id' => $contract?->id,
            'amount' => $v['amount'],
            'due_date' => $dueDate,
            'paid_date' => $paidDate,
            'status' => $status,
            'payment_method' => $v['paymentMethod'] ?? 'qr_code',
            'month' => $v['month'],
            'invoice_type' => $invoiceType,
            'billing_period_start' => $billingPeriodStart,
            'billing_period_end' => $billingPeriodEnd,
            'receipt_number' => $status === 'paid' ? $this->generateReceiptNumber() : null,
            'invoice_number' => Payment::generateInvoiceNumber(),
            'user_id' => $request->user()->id,
        ]);

        $invoiceId = $payment->invoice_number ?? ('INV-' . strtoupper(substr($payment->id, 0, 8)));
        $this->logActivity($request, 'invoice_generated', 'Invoice ' . $invoiceId . ' generated for Room ' . ($tenant->room->room_number ?? 'N/A') . ' (' . $v['month'] . ')');

        return $this->success($payment->load(['tenant', 'room']), 'Payment recorded successfully', 201);
    }

    public function update(Request $request, string $id): JsonResponse
    {
        $payment = $this->scopeByOwner(Payment::query(), $request)->find($id);
        if (!$payment) return $this->error('Payment not found', 'not_found', null, 404);

        $v = $request->validate([
            'status' => 'sometimes|in:pending,paid,overdue,cancelled,duplicate',
            'paidDate' => 'nullable|date',
            'amount' => 'sometimes|numeric|min:0',
            'paymentMethod' => 'sometimes|in:qr_code,credit_card',
        ]);

        $data = [];
        if (isset($v['status'])) {
            $data['status'] = $v['status'];
            // Auto-generate receipt number when marked as paid
            if ($v['status'] === 'paid') {
                $data['paid_date'] = $v['paidDate'] ?? now()->format('Y-m-d');
                if (!$payment->receipt_number) {
                    $data['receipt_number'] = $this->generateReceiptNumber();
                }
            }
        }
        if (isset($v['paidDate'])) $data['paid_date'] = $v['paidDate'];
        if (isset($v['amount'])) $data['amount'] = $v['amount'];
        if (isset($v['paymentMethod'])) $data['payment_method'] = $v['paymentMethod'];

        $payment->update($data);
        
        $invoiceId = $payment->invoice_number ?? ('INV-' . strtoupper(substr($payment->id, 0, 8)));
        if (isset($v['status'])) {
            if ($v['status'] === 'paid') {
                $this->logActivity($request, 'payment_completed', 'Invoice ' . $invoiceId . ' marked as paid for Room ' . ($payment->room->room_number ?? 'N/A'));
            } else if ($v['status'] === 'cancelled') {
                $this->logActivity($request, 'invoice_cancelled', 'Invoice ' . $invoiceId . ' marked as cancelled for Room ' . ($payment->room->room_number ?? 'N/A'));
            } else if ($v['status'] === 'duplicate') {
                $this->logActivity($request, 'invoice_duplicate', 'Invoice ' . $invoiceId . ' marked as duplicate for Room ' . ($payment->room->room_number ?? 'N/A'));
            }
        }

        return $this->success($payment->fresh()->load(['tenant', 'room']), 'Payment updated successfully');
    }

    public function schedule(Request $request, string $month): JsonResponse
    {
        $payments = $this->scopeByOwner(Payment::with(['tenant', 'room']), $request)
            ->where('month', $month)->get()
            ->map(function ($p) {
                $status = $p->status;
                if ($status === 'pending' && $p->invoice_type === 'monthly_rent' && $p->due_date && $p->due_date->lt(now()->startOfDay())) {
                    $status = 'overdue';
                }
                return [
                    'id' => $p->id, 'tenant' => $p->tenant->name ?? 'N/A',
                    'room' => $p->room->room_number ?? 'N/A',
                    'amount' => $p->amount, 'lateFee' => $p->late_fee,
                    'utilityAmount' => $p->utility_amount,
                    'total' => $p->total,
                    'dueDate' => $p->due_date, 'paidDate' => $p->paid_date,
                    'status' => $status,
                ];
            });

        return $this->success(['month' => $month, 'payments' => $payments]);
    }

    /**
     * GET /api/payments/{id}/receipt
     * Generate receipt data for a paid payment
     */
    public function receipt(string $id): JsonResponse
    {
        $payment = Payment::with(['tenant', 'room'])->find($id);
        if (!$payment) return $this->error('Payment not found', 'not_found', null, 404);
        if ($payment->status !== 'paid') {
            return $this->error('Receipt only available for paid payments', 'invalid_status', null, 422);
        }

        // Ensure receipt number exists
        if (!$payment->receipt_number) {
            $payment->update(['receipt_number' => $this->generateReceiptNumber()]);
            $payment->refresh();
        }

        $settings = Setting::where('user_id', $payment->user_id)->first() ?? Setting::first();

        return $this->success([
            'receiptNumber' => $payment->receipt_number,
            'date' => $payment->paid_date,
            'month' => $payment->month,
            'tenant' => [
                'name' => $payment->tenant->name ?? 'N/A',
                'phone' => $payment->tenant->phone ?? null,
                'email' => $payment->tenant->email ?? null,
            ],
            'room' => $payment->room->room_number ?? 'N/A',
            'roomType' => $payment->room->type ?? 'N/A',
            'breakdown' => [
                'rent' => (float) $payment->amount,
                'utility' => (float) $payment->utility_amount,
                'lateFee' => (float) $payment->late_fee,
                'total' => $payment->total,
            ],
            'paymentMethod' => $payment->payment_method,
            'property' => [
                'name' => $settings->property_name ?? '',
                'address' => $settings->address ?? '',
                'phone' => $settings->phone ?? '',
                'email' => $settings->email ?? '',
            ],
        ]);
    }

    /**
     * POST /api/payments/generate-invoices
     * Manually trigger invoice generation for current month
     */
    public function generateInvoices(): JsonResponse
    {
        \Artisan::call('rent:generate');
        $output = \Artisan::output();
        return $this->success(['output' => trim($output)], 'Invoice generation completed');
    }

    public function destroy(Request $request, string $id): JsonResponse
    {
        $payment = $this->scopeByOwner(Payment::query(), $request)->find($id);
        if (!$payment) return $this->error('Payment not found', 'not_found', null, 404);

        if ($payment->status === 'paid') {
            return $this->error('Paid invoices cannot be deleted. Mark as cancelled instead.', 'invalid_action', null, 400);
        }

        $invoiceId = $payment->invoice_number ?? ('INV-' . strtoupper(substr($payment->id, 0, 8)));
        $payment->delete();
        $this->logActivity($request, 'invoice_deleted', 'Invoice ' . $invoiceId . ' deleted for Room ' . ($payment->room->room_number ?? 'N/A'));
        return $this->success(null, 'Invoice soft deleted successfully');
    }

    /**
     * Generate a unique receipt number: RCP-YYYYMMDD-XXXX
     */
    private function generateReceiptNumber(): string
    {
        $date = now()->format('Ymd');
        $count = Payment::whereNotNull('receipt_number')
            ->where('receipt_number', 'like', "RCP-{$date}%")
            ->count();
        return sprintf('RCP-%s-%04d', $date, $count + 1);
    }
}
